[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "22"
  NPM_VERSION = "10.9.2"

# Environment variables for Next.js
[context.production.environment]
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME = "dp3gvxyft"
  NEXT_PUBLIC_CLOUDINARY_LOGO_FOLDER = "logos"
  NEXT_PUBLIC_CLOUDINARY_VIDEO_FOLDER = "video"
  NEXT_PUBLIC_CLOUDINARY_FAVICON_FOLDER = "favicon"

# Headers for performance optimization
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self' https://res.cloudinary.com https://cloudinary.com https://fonts.googleapis.com https://fonts.gstatic.com 'unsafe-inline' 'unsafe-eval' data: blob:; img-src 'self' https://res.cloudinary.com data: blob:; video-src 'self' https://res.cloudinary.com blob:; connect-src 'self' https://api.cloudinary.com https://fonts.googleapis.com https://fonts.gstatic.com; font-src 'self' https://fonts.gstatic.com;"

# Performance headers
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"